# """
# Django settings for longdb_dns project.

# Generated by 'django-admin startproject' using Django 2.0.7.

# For more information on this file, see
# https://docs.djangoproject.com/en/2.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/2.0/ref/settings/
# """

import os
from .settings_secret import * # for sensitive information

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ARK added 11/29/21, not actually sure if I need this since I solved the issue I was having with CSS loading by edits to the apache http.conf file
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "getdata/static"),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# this is in settings_secret.py

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

ALLOWED_HOSTS = ['152.3.43.224','152.3.88.208','127.0.0.1','10.191.27.255','www.haririlab.com','haririlab.com','67.159.93.32','rapid-1501.vm.duke.edu']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tables2',
    'templatetag_handlebars',
    'iprestrict',
    'graphos',    
    'psycopg2',
    'bootstrapform',
    'getdata',
    'checkSNP',
    'stats',
    'crispy_forms',    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# this is in settings_secret.py
#ROOT_URLCONF = 'longdb_dns.urls_dev'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            '/home/rapiduser/longdb_dns/getdata/templates',
            '/home/rapiduser/longdb_dns/stats/templates',
            '/home/rapiduser/longdb_dns/checkSNP/templates',
            '/home/rapiduser/longdb_dns/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request'
            ],
        },
    },
]


WSGI_APPLICATION = 'longdb_dns.wsgi.application'

# needed to make this work with bootstrap labels
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# this is in settings_secrety.py
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'longdb_dns',
#         'USER': 'Annchen',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',
#         'PORT': '',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_L10N = True

USE_TZ = True

IPRESTRICT_GEOIP_ENABLED = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# this is in settings_secret
#STATIC_URL = 'https://www.haririlab.com/longdb_dns/getdata/static/'  ### need this for deploy; for now only have static files in getdata app but may want to change later
LOGIN_REDIRECT_URL = '/'

